version: '2'
services:
  ganache:
    build: ganache/
    restart: on-failure
    container_name: ganache
    hostname: ganache
    ports:
      - "8545:8545"
  dapp:
    build: dapp/
    restart: on-failure
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./dapp:/usr/src/app
    stdin_open: true
    tty: true
