version: '3.5'
services:
  ganache:
    build: ganache/
    restart: on-failure
    ports:
      - "8545:8545"
    networks:
      - delphi
  dapp:
    build: dapp/
    restart: on-failure
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./dapp:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - delphi

networks:
  delphi:
    name: delphi
